# After pushing a tag (e.g., v1.0.0), GitHub Actions starts
#   1. It checks out the code at the commit where the tag was created
#   2. Creates the build package using the latest state (with updated metadata)

name: Build mpv Script Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create Package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          DIR_NAME=mpv2anki_v${VERSION}
          
          # Create main directory structure
          mkdir -p build/${DIR_NAME}/mpv/scripts build/${DIR_NAME}/mpv/script-opts
          
          # Copy MPV files
          cp mpv/input.conf build/${DIR_NAME}/mpv/
          cp mpv/mpv.conf build/${DIR_NAME}/mpv/
          cp -r mpv/scripts/mpv2anki build/${DIR_NAME}/mpv/scripts/
          cp -r mpv/script-opts/* build/${DIR_NAME}/mpv/script-opts/
          
          # Copy note types
          cp -r docs/note_types/* build/${DIR_NAME}/
          
          # Create zip from build directory
          cd build
          zip -r ../${DIR_NAME}.zip ${DIR_NAME}/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: mpv2anki v${{ steps.get_version.outputs.VERSION }}
          files: mpv2anki_${{ steps.get_version.outputs.VERSION }}.zip
          body_path: CHANGELOG.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}